### ISSUE TITLE
What type of data is packet.Data? Is it an 802.11 data frame?

### ISSUE THREAD

**Issue by TalusL** [buldo/WiFiDriver#7]
What type of data is packet.Data? Is it an 802.11 data frame

**Comment by TalusL** [comment]
Yes, it's an 802.11 data frame. I have dropped the last 4 bytes of every packet.

![image](https://github.com/buldo/WiFiDriver/assets/9034778/9d0d4b10-45da-4291-89f5-7fb991b68de7)

**Comment by buldo** [comment]
@TalusL it has to be raw 802.11 frame of any type.  
Here is very basic(and very application specific) frame parsing. https://github.com/buldo/WiFiBroadcastNet/blob/34baccad905bd1e36fdbbc21585ddd693cedc4d5/WiFiBroadcastNet/RxFrame.cs#L104

**Comment by TalusL** [comment]
@buldo How to send data？

**Comment by buldo** [comment]
@TalusL this is not implemented.  
If you need it, you have to port code from original driver.
